repos:
  - hooks:
      - id: ruff
      - id: ruff-format
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
  - hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - pre-push
    repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.1
  - hooks:
      - id: uv-lock
    repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.29
